### ISSUE TITLE
How to stop an Express script command without stopping the express server? 

### ISSUE THREAD

**Issue by saraford** [mintuz/BB8-Commander#24]
Hey all,

I'm working on a [BB-8 desktop app using electron](https://github.com/saraford/BB8-Desktop-Cmdr). I noticed that if I send the disco (or any custom) command to the Express server, the script never stops executing. 

If I use process.exit(), the Express server stops. (I'm new to Node.js). I found [one blog post](https://www.nczonline.net/blog/2014/02/04/maintainable-node-js-javascript-avoid-process-exit/) that talks about throwing an exception, but not sure if/where that can be handled gracefully. 

```
// disco.js
module.exports = function (bb8) {
    console.log('Let\'s Party!!');

    bb8.randomColor();

    setInterval(function () {
        bb8.randomColor();
    }, 1000);

    setTimeout(function () {
      process.exit();
    }, 2000);
};
```

Is there any other way to end the custom commands after a given time without fully disconnecting from the Express server?

**Comment by saraford** [comment]
P.S. for the electron app, I haven't figured out the navigation system yet. Every time he moves, it seems his internal "true north" changes to a new 0 degree orientation. E.g. his head is always in the wrong position, looking like he's moving backwards. And 90/270 turns are never what I expect them to be. I'd :heart: any ideas!

**Comment by mintuz** [comment]
Hey I'll take a look at this sometime this week. I think I've got an idea of how to solve it just need to try it out. Would you be happy with a command called "stop" or something that stops the command but keeps the connection and server running.

 Not sure throwing an error is the best idea because you would have to catch the error otherwise the script stop running.

**Comment by mintuz** [comment]
Also as for the true north issue I believe there is a function on the bb8 object that allows you to change the tracking/heading. (Can't remember the terminology).

**Comment by saraford** [comment]
> Would you be happy with a command called "stop" or something that stops the command but keeps the connection and server running

Yes! That would be perfect! :bow: 

I tried to create a command called `stop` that called `process.exit();` but that killed the server. As you said, I want to keep the connection active and the server running, but just stops the command.

> there is a function on the bb8 object that allows you to change the tracking/heading.

there's [bb8.setHeading()](https://github.com/orbotix/sphero.js/blob/fbaeeff752479e57fd1cdceb253cb639add8db89/lib/devices/sphero.js#L24) but not sure what's the correct combination of setHeading() and roll() to make what seems like a right-hand turn (hence my BB-8 desktop cmdr app to speed up calling commands). 

E.g. if I want BB-8 to roll straight ahead with his head pointing straight ahead, I'd guess I'd call

```
bb8.setHeading(0);
bb8.roll(2,0);
```

Now if i want BB-8 to turn right, do I set the new heading to the "same" 90 degrees on both? e.g.

```
bb8.setHeading(90);
bb8.roll(2,90);
```

or do I only set the new heading once? e.g.

```
bb8.setHeading(90);
bb8.roll(2,0); // because bb-8 is now already pointing 90 degrees??
```

What's I've been currently experimenting with (which isn't working as I want) is the following:

```
bb8.roll(0,90);
bb8.roll(2,90); 
```

**Comment by mintuz** [comment]
Hey sorry I've not updated you on this. Been a bit busy with stuff. I've got a solution half written and plan on getting it finished this weekend. Basically going to return the setInterval ID to the express executer and keep a reference to the ID's when you send stop. It will then stop the BB8 Unit command but not the server. just got some edge cases to solve.

**Comment by saraford** [comment]
@mintuz Hey! :wave: Thanks for the update! No worries! I've also been busy with other projects, but I really appreciate you looking into this! :smile:

**Comment by mintuz** [comment]
This has now been resolved via https://github.com/mintuz/BB8-Commander/pull/26
