### ISSUE TITLE
Unexpected Express server disconnection

### ISSUE THREAD

**Issue by JBX028** [mintuz/BB8-Commander#29]
Hi,

I don't know if this is a bug with the sphero sdk or something wrong in a way the device is connected with the express server, but after ~20 minutes, the device is suddenly and constently disconnected while the server remains alive.
I have even created a script in charge to "post" a ping command every minute but still, my bb8 becomes orange after sometime and I have to stop the server and run it again.
This issue prevent me to use my bb8 with the different workflows tool (ifttt, node-red, ms flow, etc...) I wanted to put in place.
Any idea? 

French bb8-Commander user/fan !

**Comment by mintuz** [comment]
Hello, I've not seen this behaviour myself. Have you updated the BB8 Firmware version and have you got all drivers/node versions up to date. It sounds like the bluetooth connection is timing out.

**Comment by JBX028** [comment]
Thanks for your quick reply. This is probably due to the fact that my BB8 is connected to a rasp pi/Bluetooth dongle physically a bit far because connected behind my router. Perhaps also that the pi2 is not enough powerful to support long connections and a small interuption is enought to disconnect the device.
I will try to place my device closest to the dongle and worst case, I will invest to a pi3 with the embedded bluetooth adaptor. Otherwise, the firmware version is 4.63 which is probably the most recent one because I am not prompted to update it.
At least I know this is something wrong at home !

**Comment by mintuz** [comment]
Assuming this was the case in the end, going to close issue.
